/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AuthButton {
        /**
          * icons src
         */
        "iconSrc": string;
        /**
          * Buttons text
         */
        "text": string;
    }
}
declare global {
    interface HTMLAuthButtonElement extends Components.AuthButton, HTMLStencilElement {
    }
    var HTMLAuthButtonElement: {
        prototype: HTMLAuthButtonElement;
        new (): HTMLAuthButtonElement;
    };
    interface HTMLElementTagNameMap {
        "auth-button": HTMLAuthButtonElement;
    }
}
declare namespace LocalJSX {
    interface AuthButton {
        /**
          * icons src
         */
        "iconSrc"?: string;
        /**
          * Buttons text
         */
        "text"?: string;
    }
    interface IntrinsicElements {
        "auth-button": AuthButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "auth-button": LocalJSX.AuthButton & JSXBase.HTMLAttributes<HTMLAuthButtonElement>;
        }
    }
}
